version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/myexpenses-api
      - ./app/docker/nginx/devel.conf:/etc/nginx/conf.d/default.conf
    container_name: myexpenses-nginx
  php:
    build:
      app/docker/php
    volumes:
      - .:/var/www/myexpenses-api
    container_name: myexpenses-php
  mysql:
    build:
      app/docker/mysql
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - /var/lib/mysql
    container_name: myexpenses-mysql

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    container_name: myexpenses-rabbitmq
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /data
    container_name: myexpenses-redis
#  kafka:
#    image: spotify/kafka